METnoAPI:
  user-agent: "510Global"
  download_dir: '/home/myapp/temp/downloads/Malawi/'
geoCoordinates:
  locations_of_interest: '/home/myapp/shapefiles/Malawi_API_calls_catchments_dissolved.geojson'
  catchment_areas: '/home/myapp/shapefiles/CatchmentsShapefile/'
on_local:
  output_dir: '/home/myapp/output/'
  geojson_raw: Malawi_rainfal_long_format.geojson
  tif_raw:  'Malawi_rainfall.tif'
  csv_zonal_stats: 'Malawi_rainfall_zonal.csv'
  png_images_dir: '/home/myapp/output/MWI_rainfall_mm/'
in_cloud: 
  output_dir: '/rainfall/mwi/' 
