METnoAPI:
  user-agent: "510Global"
  download_dir: '/home/rainfall/temp/downloads/'
in_cloud:
  input_dir: '/rainfall/uga/input-shape/'
  input_shape_file: 'input-shape.zip'
  output_dir: '/rainfall/uga/'
geoCoordinates:
  country_code: 'uga'
  locations_of_interest: 'uga_points.geojson'
  catchment_areas: 'kasese_adm1.geojson'
  admin3_shapefile: ''
  admin4_shapefile: ''
on_local:
  input_dir: '/home/rainfall/input-shape/'
  output_dir: '/home/rainfall/output/'
  geojson_raw: uga_rainfal_long_format.geojson
  tif_raw:  'uga_rainfall.tif'
  csv_zonal_stats: 'uga_rainfall_zonal.csv'
  png_images_dir: '/home/rainfall/output/uga_rainfall_mm/'
  csv_zonal_stats_daily: 'uga_rainfall_zonal_daily.csv'
  trigger_status: 'uga_rainfall_trigger_status.txt'
  png_bar_plot_daily_by_catchment: 'uga_rainfall_by_day_by_adm2.png'
  tif_raw_daily: 'uga_rainfall_daily.tif'
rainfall_threshold:
  one_day: 50
  three_day: 150