user-agent: "510Global"
points_API_calls_file: '/home/myapp/shapefiles/Malawi_API_calls_catchments_dissolved.geojson'
catchment_areas: '/home/myapp/shapefiles/CatchmentsShapefile/'
download_dir: '/home/myapp/temp/downloads/Malawi/'
geotable_file: '/home/myapp/temp/Malawi_rainfal_long_format.geojson'
raster_file:  '/home/myapp/temp/Malawi_rainfall.tif'
zonal_stats_catchment: '/home/myapp/Malawi_rainfall_zonal.csv'

