geoCoordinates:
  country_code: "MWI"
  adm1: FALSE 
  adm2: TRUE 
  adm3: TRUE
  adm4: TRUE
  locations_of_interest: 'Malawi_API_calls_IDREAM_dissolved.geojson'

METnoAPI:
  user-agent: "510Global"
  download_dir: '/home/rainfall/temp/downloads/'

AzureCloudStorage: 
  main_dir: '/rainfall/'
  input_dir: 'input-shape/'
  input_shape_file: 'input-shape.zip'
  output_dir: 'results/'
  full_output_dir: 'output_files/'


localStorage: 
  main_dir: /home/rainfall/
  input_dir: 'input-shape/'
  output_dir: 'results/'
  full_output_dir: 'output_files/'
  png_images_dir: 'rainfall_mm/'
  overlay_shapefile_in_png: 'adm2'

outputFiles: 
  geojson_raw: rainfall_from_metno_long_format.geojson 
  tif_raw:  'Malawi_rainfall.tif'
  csv_zonal: 'rainfal_aggregate'
  csv_zonal_daily: 'rainfal_aggregate_daily'
  trigger_status: 'trigger_status'
  png_bar_plot_daily_by_admin: 'daily_rainfal_vs_admin'
  tif_raw_daily: 'Malawi_rainfall_daily.tif'
  overlay_shapefile_in_png: ''

rainfall_threshold:
  one_day: 50
  three_day: 150

