METnoAPI:
  user-agent: "510Global"
  download_dir: '/home/rainfall_monitor/temp/downloads/Malawi/'
geoCoordinates:
  country_code: 'MWI'
  locations_of_interest: '/home/rainfall_monitor/shapefiles/Malawi_API_calls_IDREAM_dissolved.geojson'
  catchment_areas: '/home/rainfall_monitor/shapefiles/mwi_adm2_IDREAM/'
  admin3_shapefile: '/home/rainfall_monitor/shapefiles/chikwawa_adm3_IDREAM.geojson'
  admin4_shapefile: '/home/rainfall_monitor/shapefiles/10gvh_chikwawa_centroid_points.geojson'
on_local:
  output_dir: '/home/rainfall_monitor/output/'
  geojson_raw: Malawi_rainfal_long_format.geojson
  tif_raw:  'Malawi_rainfall.tif'
  csv_zonal_stats: 'Malawi_rainfall_zonal.csv'
  png_images_dir: '/home/rainfall_monitor/output/MWI_rainfall_mm/'
  csv_zonal_stats_daily: 'Malawi_rainfall_zonal_daily.csv'
  trigger_status: 'Malawi_rainfall_trigger_status.txt'
  png_bar_plot_daily_by_catchment: 'Malawi_rainfall_by_day_by_adm2.png'
  tif_raw_daily: 'Malawi_rainfall_daily.tif'
in_cloud: 
  output_dir: '/rainfall/mwi/' 
rainfall_threshold:
  one_day: 50
  three_day: 150