METnoAPI:
  user-agent: ""
  download_dir: '/home/rainfall/temp/downloads/'

geoCoordinates:
  country_code: "{ISO}"
  locations_of_interest: '{forecast_points}.geojson'
  adm1: FALSE 
  adm2: '{adm2}.geojson' 
  adm3: FALSE
  adm4: FALSE
  basemap: TRUE

rainfallThreshold:
  agg_percentile: 90
  one_day: ''
  three_day: ''

mapSettings:
  locationName: "{locationName}"
  suptitle: 'TOTAL RAINFALL FORECAST'
  titleLine1: 'Data source: ECMWF, via MET Norway'
  titleLine2: 'Forecast period:'
  titleLine3: 'Run on:'
  colorBarLabel: 'Forecasted rainfall (mm)'
  xLabel: 'Longtitude'
  yLabel: 'Latitude'
  pageWidth: 9
  pageHeight: 9
  bboxNorth: 7.1
  bboxWest: -5
  bboxSouth: 6.5
  bboxEast: -4.5

AzureCloudStorage: 
  main_dir: '/rainfall/'
  input_dir: 'input-shape/'
  input_shape_file: 'input-shape.zip'

localStorage: 
  main_dir: /home/rainfall/
  input_dir: 'input-shape/'
  output_dir: 'results/'
  raw_output: 'raw_files/'
  figures_dir: 'figures/'

outputFiles: 
  geojson_raw: 'rainfall_raw.geojson'
  tif_raw:  'rainfall.tif'
  csv_zonal: 'rainfall_aggregate'
  csv_zonal_daily: 'rainfall_aggregate_daily'
  trigger_status: 'trigger_status'
  png_bar_plot_daily_by_admin: 'daily_rainfall'
  tif_raw_daily: 'rainfall_daily.tif'


